# Generated by Django 5.0.3 on 2024-03-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindexpage_body_blogindexpage_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='date',
        ),
    ]
