# Generated by Django 5.0.3 on 2024-04-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_feedbackpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackPage',
        ),
    ]
