# Generated by Django 5.0.3 on 2024-04-16 19:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_feedbackpage'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('Data', models.DateField(default=datetime.date(2024, 4, 16), verbose_name='Data')),
                ('Título', models.CharField(max_length=150, verbose_name='Título')),
                ('Descrição', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
