# Generated by Django 5.0.3 on 2024-04-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_feedbacks_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Descrição')),
                ('slug', models.CharField(max_length=250, verbose_name='Slug')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedbacks',
        ),
    ]
