# Generated by Django 5.0.3 on 2024-04-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_feedback_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='slug',
            field=models.CharField(max_length=250, verbose_name='Slug'),
        ),
    ]
